# -*- coding: utf-8 -*-
"""Online Course Enrollment System1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W9haGWryLHsRiAfBPMYmxciDYOI-jpkR

#Online Course Enrollment System
"""

# Online Course Enrollment System

# Sample data: Students enrolled in different courses
courses = {
    "Python": ["Nayan", "Akshata", "Manswi"],
    "Data Science": ["Nayan", "Poorva", "Gauri"],
    "Web Development": ["Manswi", "Gauri", "Shreesha"]
}

# Function to add a new student to a course
def add_student(course_name, student_name):
    if course_name not in courses:
        print(f"Course {course_name} does not exist.")
        return

    if student_name in courses[course_name]:
        print(f"{student_name} is already enrolled in {course_name}.")
        return

    courses[course_name].append(student_name)
    print(f"{student_name} has been added to {course_name}.")

# Function to remove a student from a course
def remove_student(course_name, student_name):
    if course_name not in courses:
        print(f"Course {course_name} does not exist.")
        return

    if student_name not in courses[course_name]:
        print(f"{student_name} is not in {course_name}.")
        return

    courses[course_name].remove(student_name)
    print(f"{student_name} has been removed from {course_name}.")

# Function to find common students enrolled in multiple courses
def find_common_students(course1, course2):
    if course1 not in courses or course2 not in courses:
        print("One or both courses do not exist.")
        return set()  # Return an empty set if courses do not exist

    common = set(courses[course1]) & set(courses[course2])
    return common

# Function to show all unique students across all courses
def show_unique_students():
    unique_students = set()
    for students in courses.values():
        unique_students.update(students)
    return unique_students

# Main program loop
def main():
    while True:
        print("\n--- Course Enrollment System ---")
        print("1. Add Student")
        print("2. Remove Student")
        print("3. Find Common Students")
        print("4. Show Unique Students")
        print("5. Exit")

        choice = input("Select an option (1-5): ")

        if choice == '1':
            course_name = input("Enter the course name: ")
            student_name = input("Enter the student's name: ")
            add_student(course_name, student_name)

        elif choice == '2':
            course_name = input("Enter the course name: ")
            student_name = input("Enter the student's name: ")
            remove_student(course_name, student_name)

        elif choice == '3':
            course1 = input("Enter the first course name: ")
            course2 = input("Enter the second course name: ")
            common_students = find_common_students(course1, course2)
            print("Common students:", common_students)

        elif choice == '4':
            unique_students = show_unique_students()
            print("All unique students across courses:", unique_students)

        elif choice == '5':
            print("Exiting the system. Goodbye!")
            break

        else:
            print("Invalid choice. Please try again.")

# Run the program
main()